import { z } from "zod"

/**
 * Zod schema defining the structure of a weekly AI-generated market report.
 * @description This schema enforces the structure of the report generated by the AI model.
 * It ensures that all fields expected in the market report—executive summary, market overview,
 * sector analysis, risk assessment, recommendations, and referenced sources—adhere to the
 * correct types and structure.
 *
 * Usage:
 * The schema is provided to the AI report generation function to validate and shape the
 * generated output, ensuring that the returned object matches the expected report format.
 *
 * Sections:
 * - executive_summary: General sentiment and key drivers of market movements.
 * - market_overview: Near-term outlook and potential risks.
 * - sector_analysis: Promising and weak sectors with rationale for each.
 * - risk_assessment: Overall market risk and supporting notes.
 * - recommendations: Actionable stock recommendations with ticker, rationale, and allocation.
 * - assessment_sources: Sources used for analysis, including URLs and titles.
 */

export const marketReportSchema = z.object({
  notification: z.string(),
  executive_summary: z.object({
    market_sentiment: z.enum([
      "Bullish",
      "Bearish",
      "Neutral",
      "Cautiously Optimistic",
      "Cautiously Bearish",
      "Mixed",
    ]),
    key_drivers: z.array(z.string()),
  }),
  market_overview: z.object({
    near_term_outlook: z.string(),
    risks: z.string(),
  }),
  sector_analysis: z.object({
    promising_sectors: z.array(z.object({ sector: z.string(), rationale: z.string() })),
    weak_sectors: z.array(z.object({ sector: z.string(), rationale: z.string() })),
  }),
  risk_assessment: z.object({
    overall_risk: z.enum(["Low", "Medium", "High"]),
    notes: z.array(z.string()),
  }),
  recommendations: z.array(
    z.union([
      z.object({
        asset_type: z.literal("stock").default("stock"),
        ticker: z.string(),
        rationale: z.string(),
        allocation: z.number(),
        action: z.enum(["buy", "sell"]),
      }),
      z.object({
        asset_type: z.literal("option_vertical_spread"),
        underlying_ticker: z.string(),
        option_type: z.enum(["call", "put"]),
        expiration_date: z.string(),
        contracts: z.number().int().positive(),
        allocation: z.number(),
        rationale: z.string(),
      }),
    ]),
  ),
  assessment_sources: z.array(z.object({ url: z.string().url(), title: z.string() })),
})

export type MarketReportSchema = z.infer<typeof marketReportSchema>
